checkbox
js-tasks-ru/htmlcss-20220519_ilya81 pull request #18
Opened 2022-06-28 19:59 UTC by iVoloskov

2022-06-28 20:00 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-06-29 17:54 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-07-01 21:16 UTC, GSemikozov requested changes

2022-07-01 21:16 UTC, GSemikozov commented on 07-lection5/01-checkbox/checkbox.css
> +.checkboxes__preview {
элемент содержащий в себе блок? нет, это ошибка)
просто вспомогательные стили? тогда класс оформляем как не привязанный к блоку и выносим в style страницы

2022-07-01 21:16 UTC, GSemikozov commented on 07-lection5/01-checkbox/checkbox.css
> +.checkbox-main-title {
тоже лишнее (та же история что и с .checkboxes__preview)

2022-07-05 05:58 UTC, iVoloskov commented on 07-lection5/01-checkbox/checkbox.css
> +.checkboxes__preview {
Ошибка касается только этого конкретного случая?
Вообще, на практике, может один (допустим довольно большой) блок или его элементы содержать более мелкие блоки внутри себя? Я был уверен, что да. Просто твой комментарий ввел в сомнения.

2022-07-05 05:58 UTC, iVoloskov reviewed
Review needed

2022-07-05 10:39 UTC, GSemikozov commented on 07-lection5/01-checkbox/checkbox.css
> +.checkboxes__preview {
здесь проблема в том, что это вспомогательные стили, они не относятся напрямую к блоку .checkbox

2022-07-05 10:39 UTC, GSemikozov approved these changes

2022-07-05 10:39 UTC, merged