inputs
js-tasks-ru/htmlcss-20220519_ilya81 pull request #21
Opened 2022-06-30 17:47 UTC by iVoloskov

2022-06-30 17:57 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-07-04 18:56 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-07-04 19:09 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-07-04 19:11 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-07-04 19:18 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-07-04 19:19 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-07-04 19:22 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-07-04 19:23 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-07-05 05:49 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-07-05 10:42 UTC, GSemikozov requested changes

2022-07-05 10:42 UTC, GSemikozov commented on 07-lection5/04-input/input.css
> +    width: 350px;
инпут может жестко не фиксировать по ширине

2022-07-05 10:42 UTC, GSemikozov commented on 07-lection5/04-input/input.css
> +.form-group_success .form-group__success-mark,
.form-group__success-mark + .form-group__error-mark можно описать отдельно, а здесь уже просто показывать display: block;

2022-07-05 10:44 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-07-05 10:47 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-07-05 10:48 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-07-05 11:08 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-07-05 11:17 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-07-06 10:06 UTC, GSemikozov approved these changes

2022-07-06 10:06 UTC, merged