tabs based on radio inputs
js-tasks-ru/htmlcss-20220519_ilya81 pull request #22
Opened 2022-07-07 18:40 UTC by iVoloskov

2022-07-07 18:41 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-07-10 08:57 UTC, GSemikozov requested changes

2022-07-10 08:57 UTC, GSemikozov commented on components/tabs/tabs.css
> +.tabs__content_all {
75-89 строки можно объединить и перечислить все селекторы, а потом задать один общий стиль display: none;

2022-07-10 08:57 UTC, GSemikozov commented on components/tabs/tabs.css
> +#all-components-tab:checked ~ .tabs__container .tabs__content_all {
и тут по аналогии

2022-07-11 08:57 UTC, GSemikozov approved these changes

2022-07-11 08:57 UTC, merged