skeleton
js-tasks-ru/htmlcss-20220519_ilya81 pull request #5
Opened 2022-05-28 17:26 UTC by iVoloskov

2022-05-28 17:27 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-05-29 20:16 UTC, GSemikozov requested changes

2022-05-29 20:16 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +.avatar-mini {
.skeleton__avatar-mini

2022-05-29 20:16 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +.skeleton-rows {
.skeleton__rows

2022-05-29 20:16 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +.fake-line {
.skeleton__fake-line

2022-05-29 20:16 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +.fake-line_small {
.skeleton__fake-line_small

и ниже

2022-05-30 08:37 UTC, iVoloskov reviewed
Review Request

2022-05-30 08:37 UTC, iVoloskov commented on 04-lection2/02-skeleton/skeleton.css
> +.skeleton-rows {
согласен, исправил

2022-05-30 08:37 UTC, iVoloskov commented on 04-lection2/02-skeleton/skeleton.css
> +.avatar-mini {
Идея была в том, чтобы сделать avatar-mini как отдельный блок. То есть для какого-то реального проекта я бы сделал так, чтобы иметь возможность заюзать .avatar-mini в других частях кода.

2022-05-30 08:37 UTC, iVoloskov commented on 04-lection2/02-skeleton/skeleton.css
> +.fake-line {
Здесь ситуация аналогичная avatar-mini. Хотел заимплементить, как отдельный блок.

2022-05-30 08:37 UTC, iVoloskov commented on 04-lection2/02-skeleton/skeleton.css
> +.fake-line_small {
Соответственно .fake-line_small - это модификатор блока

2022-05-30 08:57 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +.avatar-mini {
но - аватар как компонент мы будем верстать отдельно, в данном случае - это просто элемент скелетона

2022-05-30 08:58 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +.avatar-mini {
и если уж верстаем как отдельный блок - то тогда и в отдельном файле стилей, поскольку в данном - мы описываем блок .skeleton )

2022-05-30 08:59 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +.fake-line {
в этом нет смысла) но коммент выше - актуален

2022-05-30 11:29 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-05-30 11:39 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-05-30 11:40 UTC, iVoloskov commented on 04-lection2/02-skeleton/skeleton.css
> +.avatar-mini {
ок, понял. Поменял на элемент

2022-05-30 11:40 UTC, iVoloskov commented on 04-lection2/02-skeleton/skeleton.css
> +.fake-line {
Поменял на элемент

2022-05-30 11:40 UTC, iVoloskov commented on 04-lection2/02-skeleton/skeleton.css
> +.fake-line_small {
Исправил

2022-05-30 15:20 UTC, GSemikozov approved these changes

2022-05-30 15:20 UTC, merged