histogram
js-tasks-ru/htmlcss-20220519_ilya81 pull request #6
Opened 2022-05-28 18:11 UTC by iVoloskov

2022-05-28 18:11 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-05-29 20:17 UTC, GSemikozov requested changes

2022-05-29 20:17 UTC, GSemikozov commented on 04-lection2/01-histogram/index.html
> +                <div class="histogram__view-link">
здесь сразу можно `<a>`

2022-05-30 05:48 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-05-30 06:06 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-05-30 06:14 UTC, iVoloskov commented on 04-lection2/01-histogram/index.html
> +                <div class="histogram__view-link">
исправил

2022-05-30 06:14 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-05-30 08:09 UTC, GSemikozov approved these changes

2022-05-30 08:10 UTC, merged